### PR TITLE
Implemented faster bulk block updating for 1.7.x series servers

### PR DESCRIPTION
**Pull request by rmichela**
In this PR I implemented an improved algorithm for bulk updating and relighting blocks for 1.7.x series servers. As part of Mojang's massive 1.7 rewrite, adding a block to the world ended up automatically relighting that block. This works individually when placed by a player, but falls apart when hundreds of thousands of blocks are being changed at the same time. To make bulk block updating work, I did the following:
- Lifted the NMS code responsible out of the core Minecraft code into each NMSHandler.
- Split the NMS code into block update and block relight code.
- Applied additional optimizations to the block relight code that only make sense in the context of bulk operations
  - A block cannot affect the relighting calculations if it is completely surrounded by opaque blocks.
- Created a new RelightStrategy called HYBRID
  - With RelightStrategy.HYBRID, block changes are sent to the client immediately, but relight calculations are sent when they are ready.

### CODE REVIEW

**Comment by desht** [comment]
I would like to pull this, but a couple of things:
1. Minor - can you rebase it on the latest dhutils code please (version is up to 2.16.0-SNAPSHOT)
2. There seems to be an awful lot of duplicated code.  I believe (but you can confirm) that the a() methods are identical for the three 1.7 revisions (IIRC there haven't been any obfuscation changes in this are over the three revisions).  How about moving the common code into an abstract 1.7 superclass?

**Comment by rmichela** [comment]
1. I rebased to master before issuing the PR. Is this the correct branch for the latest code?
2. I looked into creating a base class. While the code looks identical, none of the types are the same because of the craftbukkit version stamping shenanigans. You can't actually create a base class because there three sets of identically named, unrelated classes.

**Comment by desht** [comment]
Sorry for the delay in response, been away for a bit.
1. I'm looking at Lib/pom.xml in particular, where your PR resets the version to 2.12.0-SNAPSHOT and the Vault dependency version to LATEST (it was v1.3.01 when you raised the PR, but I've just updated that to v1.4) - https://github.com/desht/dhutils/pull/8/files
2. Yeah, good point :(

**Comment by rmichela** [comment]
I'll fix the pom.xml. That was an oversight.

**Comment by rmichela** [comment]
I fixed the pom.xml and rebased to the latest master.

**Comment by desht** [comment]
Pulled, thanks!

**Pull request merged**
