### PR TITLE
Added data value support for Spawn Eggs

### PR DESCRIPTION
**Pull request by ghost**
Previously the string returned would be brief, and just display 'Spawn Egg', this will now support data values, for example a Mooshroom Egg will return a string of 'Spawn Mooshroom'.

### CODE REVIEW

**Comment by desht** [comment]
Is that what the vanilla client displays, though? (I can't remember)

The intention here was always to mimic the client as much as possible (although showing more spawn egg information is not a bad idea...)

**Comment by ghost** [comment]
Yes it does

http://prntscr.com/3x1q32

**Comment by desht** [comment]
OK, cool.  The indentation of your changes looks off by a space, though (I know, it's a small thing but I'm picky :)

**Comment by ghost** [comment]
I noticed the same thing, I tried to fix it in the 2nd commit, but it seemed to be aligned correctly in the editor strangely

**Comment by desht** [comment]
Pulled, thanks!  Indentation seems OK, must have been github preview lying to me.

**Pull request merged**
